### POST request to create new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Project Grind",
  "address": "123 Main Street, New York",
  "dateOfBirth": "1999-12-09",
  "registeredDate": "2025-11-02"
}

###