### POST request to create new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Test Patient2 with billing account with new one",
  "email": "test_billingAccount3@gmail.com",
  "address": "1235 Main Street, New York",
  "dateOfBirth": "1999-12-09",
  "registeredDate": "2025-11-02"
}

###