### POST request to create new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Test analytics test",
  "email": "analytics@gmail.com",
  "address": "1235 Main Street, New York",
  "dateOfBirth": "1999-12-09",
  "registeredDate": "2025-11-02"
}

###