spring.application.name=patient-service

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true


logging.level.root=info
server.port=4000